### ISSUE TITLE
[Flink AI Flow] No state check before stopping a workflow execution

### ISSUE THREAD

**Issue by bgeng777** [flink-extended/dl-on-flink#466]
### Describe the bug
When we submit a workflow whose any job contains a periodic config, then we call `stop_workflow_execution` to stop it. It will work. However, if we submit the workflow again and try to stop all workflow executions of this workflow, we will meet a such error:
```
Traceback (most recent call last):
  File "/Users/kenken/bella/lib/python3.7/site-packages/airflow/contrib/jobs/event_based_scheduler_job.py", line 624, in _execute
    self._run_scheduler_loop()
  File "/Users/kenken/bella/lib/python3.7/site-packages/airflow/contrib/jobs/event_based_scheduler_job.py", line 643, in _run_scheduler_loop
    should_continue = self.scheduler.schedule()
  File "/Users/kenken/bella/lib/python3.7/site-packages/airflow/contrib/jobs/event_based_scheduler_job.py", line 165, in schedule
    self._remove_periodic_events(event.run_id)
  File "/Users/kenken/bella/lib/python3.7/site-packages/airflow/utils/session.py", line 65, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/kenken/bella/lib/python3.7/site-packages/airflow/contrib/jobs/event_based_scheduler_job.py", line 238, in _remove_periodic_events
    self.periodic_manager.remove_task(run_id, task.task_id)
  File "/Users/kenken/bella/lib/python3.7/site-packages/airflow/contrib/jobs/periodic_manager.py", line 109, in remove_task
    self.sc.remove_job(job_id=self._generate_job_id(run_id, task_id))
  File "/Users/kenken/bella/lib/python3.7/site-packages/apscheduler/schedulers/base.py", line 621, in remove_job
    raise JobLookupError(job_id)
apscheduler.jobstores.base.JobLookupError: 'No job by the id of manual__2021-08-04T07:27:52.741875+00:00:evaluate was found'
```

After diving into the codes, there are 2 reasons of this bug:
1. In `ai_flow_plugins.scheduler_plugins.airflow.airflow_scheduler.AirFlowScheduler def stop_workflow_execution(self, workflow_execution_id: str)` method, we do not check the state of the workflow executions during the query.
2. We do not handle exception correctly in `airflow/contrib/jobs/periodic_manager.py:109`

To fix the issue, I think we should take actions in above 2 places.

#### Operating system
Macos

#### Database
MySQL

#### Python version
3.7.10

### To Reproduce
See [Describe the bug](###Describe-the-bug)

### Expected behavior
The stop operation should not be applied to stopped executions.

**Comment by Sxnan** [comment]
AIFlow has been moved to https://github.com/flink-extended/ai-flow.

Please reopen the issue there if necessary.
