### ISSUE TITLE
worker重启问题

### ISSUE THREAD

**Issue by xdyun** [flink-extended/dl-on-flink#720]
实际使用中发现worker会出现自动重启的情况，日志如下：
- TimeoutScanThread thread=246's currentBufferSize = 0
2022-03-30 09:20:45,411 INFO  [1097] [com.alibaba.flink.ml.cluster.rpc.NodeServiceImpl.nodeRestart(NodeServiceImpl.java:67)]  - worker:33 receive restart
2022-03-30 09:20:49,308 WARN  [983] [com.alibaba.flink.ml.cluster.node.runner.NodeHeartBeatRunner.run(NodeHeartBeatRunner.java:56)]  - worker:33 heartbeat wrong version 1648597416162, terminating heartbeat thread and restart tf node
2022-03-30 09:20:49,308 INFO  [983] [com.alibaba.flink.ml.cluster.rpc.AbstractGrpcClient.close(AbstractGrpcClient.java:33)]  - close AppMaster client
2022-03-30 09:20:49,310 INFO  [983] [com.alibaba.flink.ml.cluster.rpc.AbstractGrpcClient.close(AbstractGrpcClient.java:38)]  - AppMaster client channel termination: true
2022-03-30 09:20:54,363 INFO  [287] [com.alibaba.flink.ml.cluster.rpc.NodeServer.run(NodeServer.java:240)]  - am command: restart
2022-03-30 09:20:54,363 INFO  [287] [com.alibaba.flink.ml.cluster.rpc.NodeServer.stopMLRunner(NodeServer.java:272)]  - begin stop node:worker:33
2022-03-30 09:20:54,363 WARN  [305] [com.alibaba.flink.ml.cluster.node.runner.python.ProcessPythonRunner.runProcess(ProcessPythonRunner.java:140)]  - worker:33 interrupted, killing the process

**Comment by Sxnan** [comment]
能再提供一些一下具体的信息吗？

**Comment by Sxnan** [comment]
从你给的日志上看，应该是某个 worker 挂掉了。

能再提供一些具体的信息吗？ 
- 你是在本地运行还是在分布式的 Flink 集群上运行
- 完整的 TM 日志 （可以通过附件的方式）
- 如果可以的话，可以提供一下作业的代码（包括 Flink 作业代码和训练脚本的代码）

我希望可以收集更多的信息，最好能够复现出来，帮忙排查问题

**Comment by xdyun** [comment]
> 

在分布式的flink集群上运行，从目前重启的规律上来看，是worker在处理大量数据的时候（例如加载模型）会出现这种问题。是否worker在繁忙的时候，无法回复心跳导致了框架认为worker已经挂掉？

**Comment by Sxnan** [comment]
> > 
> 
>     1. 从worker的日志来看，没有抛出异常的日志。
> 
>     2. 整个任务是在分布式的flink集群上运行，从目前重启的规律上来看，是worker在处理大量数据的时候（例如加载模型，大概会阻塞worker 1分钟）会出现这种问题。是否worker在繁忙的时候，无法回复心跳导致了框架认为worker已经挂掉？

1. 我再确认一下 worker 日志没有抛出日常是指所有的 tm 都没有错误的日志吗？也有可能是别的 worker restart 了，导致这里的 33 被重启了。
2. 加载模型是在 python 进程加载还是在 java 进程，如果是 python 进程的话，即使阻塞了也不会导致停止回复心跳。

**Comment by xdyun** [comment]
> > > 
> > 
> > 
> > ```
> > 1. 从worker的日志来看，没有抛出异常的日志。
> > 
> > 2. 整个任务是在分布式的flink集群上运行，从目前重启的规律上来看，是worker在处理大量数据的时候（例如加载模型，大概会阻塞worker 1分钟）会出现这种问题。是否worker在繁忙的时候，无法回复心跳导致了框架认为worker已经挂掉？
> > ```
> 
> 1. 我再确认一下 worker 日志没有抛出日常是指所有的 tm 都没有错误的日志吗？也有可能是别的 worker restart 了，导致这里的 33 被重启了。
> 2. 加载模型是在 python 进程加载还是在 java 进程，如果是 python 进程的话，即使阻塞了也不会导致停止回复心跳。

1. worker日志没有抛出异常，确实是其他的worker导致的，目前看是其他的tm里有一个异常日志
2022-03-31 15:32:36,835 ERROR [302] [com.alibaba.flink.ml.cluster.node.runner.CommonMLRunner.run(CommonMLRunner.java:244)]  - Got exception during python running
com.alibaba.flink.ml.util.MLException: worker:25 python process exited with code 137
	at com.alibaba.flink.ml.cluster.node.runner.python.ProcessPythonRunner.runProcess(ProcessPythonRunner.java:137)
	at com.alibaba.flink.ml.cluster.node.runner.python.ProcessPythonRunner.runScript(ProcessPythonRunner.java:118)
	at com.alibaba.flink.ml.cluster.node.runner.CommonMLRunner.runScript(CommonMLRunner.java:258)
	at com.alibaba.flink.ml.cluster.node.runner.CommonMLRunner.run(CommonMLRunner.java:234)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2. 加载模型是在python进程，心跳这块应该没问题

**Comment by Sxnan** [comment]
exited with code 137 一般是内存不够导致进程被杀

**Comment by Sxnan** [comment]
I am closing the issue. Feel free to reopen the issue if there are any further questions.
